config/routes.rb
Rails.application.routes.draw do

  resources :welcome, only: :index
  root 'welcome#index'
  get "welcome/splash" => "welcome#splash"

  get "users/unknown_user" => "users#unknown_user"

  devise_scope :user do
    get "users/sign_up", to: "registrations#register", as: "new_user_registration_path"
    post "users/sign_up", to: "registrations#create", as: "user_registration"
  end
  devise_scope :user do
    get "users/sign_in", to: "sessions#new", as: "new_user_session_path"
    post "users/sign_in", to: "sessions#create", as: "user_session"
  end


  get '/users/finish_signup' => 'users#show_finish_signup'
  post "/users/finish_signup" => "users#finish_signup"

  post "/followings" => "followings#create"
  delete "/followings" => "followings#destroy"

  delete "/restaurants/:restaurant_id/bookmarks" => "bookmarks#destroy"

  # search
  get "search" => 'restaurants#search'
  get "search/filter" => 'restaurants#filter'

  resources :articles, except: :destroy
  resources :restaurants, except: [:index, :destroy] do
    resources :quick_takes, only: [:new, :create]
    resources :reviews
    resources :bookmarks, only: [:create]
    resources :visits, only: [:create]
    resources :specialties, only: [:create]
  end


  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks", sessions: "sessions"}

  get "/users/top-reviewers" => 'users#top_reviewers', as: :top_reviewers

  get "/users/invite" => 'users#invite'
  post "/admins/invite" => 'users#reviewer_invite'
  post "/users/invite" => "users#user_invite"
  resources :users, only: [:show] do
    resources :profiles, only: [:new, :create, :edit, :update]
  end

  post 'reviews/:id/upvote'       => 'reviews#upvote', as: :upvote_review
  post 'reviews/:id/downvote'     => 'reviews#downvote', as: :downvote_review
  post 'comments/:id/upvote'      => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote'    => 'comments#downvote', as: :downvote_comment
  post 'specialties/:id/upvote'   => 'specialties#upvote', as: :upvote_specialty
  post 'specialties/:id/downvote' => 'specialties#downvote', as: :downvote_specialty
  post 'restaurants/:restaurant_id/reviews/:id/comments' => 'comments#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include ContentHelper
  belongs_to :author, class_name: "User"

  validates :title, :content, :author_id, presence: true

  def get_preview
    self.content.split(" ")[0..75].join(" ")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  include ApplicationHelper

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authorized_reviewer?, only: [:new, :create, :edit, :update]

  def index
    @articles = Article.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      flash[:errors] = @article.errors.full_messages
      redirect_to new_article_path
    end
  end

  def show
  end

  def edit
    must_be_owner(@article.author_id)
  end

  def update
    must_be_owner(@article.author_id)
    if @article.update_attributes(article_params)
      redirect_to @article
    else
      flash[:errors] = @article.errors.full_messages
      redirect_to edit_article_path
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content).merge(author_id: current_user.id)
  end
end

app/views/articles/_articles.html.erb
<%= paginate @articles %>

  <% @articles.each do |article| %>
    <div class="article-grouping">
      <h3 class="header-link"><%= link_to "#{article.title}", article_path(article) %></h3>
      <p>By <%= link_to "#{article.author.username}", user_path(article.author) %></p>
  <% end %>

<%= "No articles found" if @articles.empty? %>

<%= paginate @articles %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, size: 50 %>

  <%= f.label :content %>
  <%= f.text_area :content, cols: "50", rows: "5" %>

  <p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: '/errors', layout: false %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-lg-10 col-lg-offset-1 article-form">
      <h1>Edit Your Article Here</h1>
        <%= render "form" %>
        <p><%= link_to "Back to Article Without Saving", article_path(@article) %></p>
        <%= link_to "Return to Profile", user_path(current_user) %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-11 col-xs-offset-1">
      <h1>Most Recent Articles</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div id="articles-container">
        <%= render "articles" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render partial: "/errors" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-lg-10 col-lg-offset-1 article-form">
      <h1>Upload Your Article Here</h1>
        <%= render "form" %>
        <%= link_to "Return to Profile Without Saving", user_path(current_user) %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid review-container">
  <div class="row">
    <div class="col-xs-12 col-lg-offset-1 col-lg-10">
      <h2 class="header-link text-capitalize"><%= link_to "#{@article.title}", article_path(@article) %></h2>
      <h4 class="review-byline">By <%= link_to "#{@article.author.profile.full_name}", user_path(@article.author) %></h4>
      <h5 class="plain text-capitalize"><%= @article.author.profile.affiliation %></h5>
      <p class="article-text"><%= @article.content %></p>
      <p class="end-link"><%= link_to "Jump to Recent Articles", articles_path %></p>
    </div>
  </div>
</div>