config/routes.rb
Rails.application.routes.draw do

  resources :welcome, only: :index
  root 'welcome#index'
  get "welcome/splash" => "welcome#splash"

  get "users/unknown_user" => "users#unknown_user"

  devise_scope :user do
    get "users/sign_up", to: "registrations#register", as: "new_user_registration_path"
    post "users/sign_up", to: "registrations#create", as: "user_registration"
  end
  devise_scope :user do
    get "users/sign_in", to: "sessions#new", as: "new_user_session_path"
    post "users/sign_in", to: "sessions#create", as: "user_session"
  end


  get '/users/finish_signup' => 'users#show_finish_signup'
  post "/users/finish_signup" => "users#finish_signup"

  post "/followings" => "followings#create"
  delete "/followings" => "followings#destroy"

  delete "/restaurants/:restaurant_id/bookmarks" => "bookmarks#destroy"

  # search
  get "search" => 'restaurants#search'
  get "search/filter" => 'restaurants#filter'

  resources :articles, except: :destroy
  resources :restaurants, except: [:index, :destroy] do
    resources :quick_takes, only: [:new, :create]
    resources :reviews
    resources :bookmarks, only: [:create]
    resources :visits, only: [:create]
    resources :specialties, only: [:create]
  end


  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks", sessions: "sessions"}

  get "/users/top-reviewers" => 'users#top_reviewers', as: :top_reviewers

  get "/users/invite" => 'users#invite'
  post "/admins/invite" => 'users#reviewer_invite'
  post "/users/invite" => "users#user_invite"
  resources :users, only: [:show] do
    resources :profiles, only: [:new, :create, :edit, :update]
  end

  post 'reviews/:id/upvote'       => 'reviews#upvote', as: :upvote_review
  post 'reviews/:id/downvote'     => 'reviews#downvote', as: :downvote_review
  post 'comments/:id/upvote'      => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote'    => 'comments#downvote', as: :downvote_comment
  post 'specialties/:id/upvote'   => 'specialties#upvote', as: :upvote_specialty
  post 'specialties/:id/downvote' => 'specialties#downvote', as: :downvote_specialty
  post 'restaurants/:restaurant_id/reviews/:id/comments' => 'comments#create'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :must_be_logged_in, only: [:reviewer_invite, :user_invite, :invite]
  before_filter :must_be_admin, only: [:reviewer_invite]
  before_filter :find_user, only: [:show]
  before_filter :user_exists?, only: [:show]


  def invite
    @user = User.new
  end

  def user_invite
    User.invite_user!({email: params[:user][:email]}, current_user)
    redirect_to root_path
  end

  def reviewer_invite
    User.invite_reviewer!({email: params[:user][:email], role: "reviewer"}, current_user)
    redirect_to root_path
  end

  def show
    @profile = Profile.find_by(user_id: params[:id])
    @new_user = User.new
  end

  def unknown_user
  end

    
    

  def top_reviewers
    @top_reviewers = User.top_ten_reviewers
  end

end

app/views/users/_invite.html.erb
<h4><%= t "devise.invitations.new.header" %></h4>

<%= form_for new_user, :url => "/users/invite", :html => {:method => :post, class: "form-inline"} do |f| %>

	<% new_user.class.invite_key_fields.each do |field| -%>
	  <%= f.label field %>
	  <%= f.text_field field %>

	<% end %>



	<button type="submit" formaction="/users/invite"> Invite user </button>
	<% if admin? %>
  	<button type="submit" formaction="/admins/invite"> Invite as reviewer </button>
	<% end %>
  </p>
<% end %>

app/views/users/_reputation.html.erb
<% unless user.admin? %>
  <div class="user-score btn">
    <strong>
      <% if user.reviewer? %>
        <%= user.reviewer_reputation %>
      <% else %>
        <%= user.user_reputation %>
      <% end %>
    </strong>
  </div>
<% end %>

app/views/users/_user.html.erb
<div>
	<h4><%= user.username || user.email %>'s 
		<% end %><h4>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2 col-md-1">
			<%= image_tag avatar_url(@user), class: "img-responsive" %>
		</div>
		<div class="col-xs-10 col-md-11">
			<p class="h2 profile-header"><%= @user.username %>
				<span><%= render partial: "reputation", locals: { user: @user } %>


				<% if @profile %>
					<!-- Follow/Unfollow Button for Logged-In Users -->
					<% if user_signed_in?  && !owner?(@profile.user_id) && !current_user.follows?(@profile.user_id) %>
						<%= render partial: "followings/follow", layout: false, locals: { resource: @profile } %>
					<% elsif user_signed_in? && !owner?(@profile.user_id) %>
		        <%= render partial: "followings/unfollow", layout: false, locals: { resource: @profile } %>
					<% end %>
				<% end %>
			</span>
			</p>
		</div>
	</div> <!-- ends first row -->

	<div class="row">
		<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
				<!-- Profile Editing Buttons -->
			<% if owner?(params[:id]) %>
				<%= link_to "Edit account info", edit_user_registration_path, :class => "btn btn-default edit-profile" %>
			<% end %>

			<% if @profile %>
				<% if owner?(@profile.user_id) %>
					<%= link_to "Edit profile", edit_user_profile_path(@user, @user.profile), :class => "btn btn-default edit-profile" %>
			 		<!-- if the user is the owner, they have a profile, and they are an authorized reviewer/admin -->
					<% if @user.reviewer? || @user.admin? %>
						<%= link_to "Add Restaurant", new_restaurant_path, :class => "btn btn-success edit-profile" %>
							<%= link_to "Create New Article", new_article_path, :class => "btn btn-success edit-profile" %>
					<% end %>
				 <% end%>
			<% end %>

			<% if @profile %>
				<%= render partial: "profiles/show", layout: false, locals: {profile: @profile, user: @user } %>
			<% elsif current_user && (current_user.id == params[:id].to_i) %>
				 <%= link_to'Create profile', new_user_profile_path(current_user), :class => "btn btn-default edit-profile" %>
			<% end %>
		</div>
	</div>

	<!-- Invite Forms -->
	<% if owner?(params[:id]) %>
		<div class="row">
			<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
					<hr />
					<%= render partial: "users/invite", locals: { new_user: @new_user, profile: @profile } %>
					<hr />
			</div>
		</div>
	<% end %>

	<% if @user.reviewer? || @user.admin? %>
		<div class="row">
			<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
				<% unless @user.reviews.empty? %>
					<h3>Reviews:</h3>
						<ul class="writings-list">
						<% @user.reviews.each do |review| %>
							<li><%= link_to "#{review.title}", restaurant_review_path(review.restaurant, review), :class => "text-capitalize" %>
								<% if current_user && (current_user.id == params[:id].to_i) %>
									<%= link_to "Edit review", edit_restaurant_review_path(review.restaurant, review), :class => "btn btn-default btn-xs" %>
								<% end %>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
				<% unless @user.articles.empty? %>
					<h3>Articles:</h3>
						<ul class="writings-list">
						<% @user.articles.each do |article| %>
							<li><%= link_to "#{article.title}", article_path(article), :class => "text-capitalize" %>
								<% if current_user && (current_user.id == params[:id].to_i) %>
									<%= link_to "Edit article", edit_article_path(article), :class => "btn btn-default btn-xs" %>
								<% end %>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-10 col-med-11 col-xs-offset-2 col-md-offset-1">
				<% unless @user.followers.empty? %>
					<h3>Followed By:</h3>
						<% @user.followers.each do |follower| %>
							<div class="gravatar-img">
							<%= link_to image_tag(avatar_url(follower), alt: follower.username, class: "gravatar-img"), user_path(follower) %>
							<p class="social-usernames hidden-xs"><%= follower.username %></p>
							</div>
						<% end %>
				<% end %>
			</div>
		</div>

	<% end %>

	<div class="row">
		<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
			<% unless @user.followed_users.empty? %>
				<h3>Followed Users:</h3>
					<% @user.followed_users.each do |followed_user| %>
						<div class="gravatar-img">
							<%= link_to image_tag(avatar_url(followed_user), alt: followed_user.username, class: "gravatar-img"), user_path(followed_user) %>
						<p class="social-usernames hidden-xs"><%= followed_user.username %></p>
						</div>
					<% end %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
			<% unless @user.visited_restaurants.empty? %>
				<h3>Visited Restaurants:</h3>
					<ul>
					<% @user.visited_restaurants.each do |visited_restaurant| %>
						<li><%= link_to "#{visited_restaurant.name}", restaurant_path(visited_restaurant) %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>

		<div class="row">
		<div class="col-xs-10 col-md-11 col-xs-offset-2 col-md-offset-1">
			<% unless @user.bookmarked_restaurants.empty? %>
				<h3>Bookmarked Restaurants:</h3>
					<ul>
					<% @user.bookmarked_restaurants.each do |bookmarked_restaurant| %>
						<li><%= link_to "#{bookmarked_restaurant.name}", restaurant_path(bookmarked_restaurant) %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>

</div>

app/views/users/top_reviewers.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-11 col-xs-offset-1">
      <h1>Top-Rated Foodie Reviewers</h1>
    </div>
  </div>

  <table>
  <% @top_reviewers.each_with_index do |top_reviewer, index| %>
    <tr>
      <td class="col-sm-1 col-sm-offset-1 col-xs-2 reviewer-icon">
        <%= image_tag avatar_url(top_reviewer), class: "img-responsive reviewer-avatar" %>
      </td>

  <!-- Mobile display -->
      <td class="col-xs-1 reviewer-rank">
        <h2><%= "#{index + 1}." %></h2>
      </td>
      <td class="col-xs-9">
        <h2 class="header-link"><%= link_to "#{top_reviewer.username}", user_path(top_reviewer) %>
          <span><%= render partial: "reputation", locals: { user: top_reviewer } %></span>
        </h2>

        <p><%= top_reviewer.reviews.count %> total reviews.<p>
        <p>Read their review of the restaurant <%= link_to "#{top_reviewer.reviews.last.restaurant.name}", restaurant_path(top_reviewer.reviews.last.restaurant) %> by clicking <%= link_to "here", restaurant_review_path(top_reviewer.reviews.last.restaurant, top_reviewer.reviews.last) %>.</p>
        <p>Or visit their <%= link_to "profile", user_path(top_reviewer) %> to see all their reviews.</p>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/unknown_user.html.erb
<div class="col-xs-12 col-lg-offset-1 col-lg-10">
<h2> Unknown User </h2>
<p> User profile no longer exists. </p>
</div>