config/routes.rb
Rails.application.routes.draw do

  resources :welcome, only: :index
  root 'welcome#index'
  get "welcome/splash" => "welcome#splash"

  get "users/unknown_user" => "users#unknown_user"

  devise_scope :user do
    get "users/sign_up", to: "registrations#register", as: "new_user_registration_path"
    post "users/sign_up", to: "registrations#create", as: "user_registration"
  end
  devise_scope :user do
    get "users/sign_in", to: "sessions#new", as: "new_user_session_path"
    post "users/sign_in", to: "sessions#create", as: "user_session"
  end


  get '/users/finish_signup' => 'users#show_finish_signup'
  post "/users/finish_signup" => "users#finish_signup"

  post "/followings" => "followings#create"
  delete "/followings" => "followings#destroy"

  delete "/restaurants/:restaurant_id/bookmarks" => "bookmarks#destroy"

  # search
  get "search" => 'restaurants#search'
  get "search/filter" => 'restaurants#filter'

  resources :articles, except: :destroy
  resources :restaurants, except: [:index, :destroy] do
    resources :quick_takes, only: [:new, :create]
    resources :reviews
    resources :bookmarks, only: [:create]
    resources :visits, only: [:create]
    resources :specialties, only: [:create]
  end


  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks", sessions: "sessions"}

  get "/users/top-reviewers" => 'users#top_reviewers', as: :top_reviewers

  get "/users/invite" => 'users#invite'
  post "/admins/invite" => 'users#reviewer_invite'
  post "/users/invite" => "users#user_invite"
  resources :users, only: [:show] do
    resources :profiles, only: [:new, :create, :edit, :update]
  end

  post 'reviews/:id/upvote'       => 'reviews#upvote', as: :upvote_review
  post 'reviews/:id/downvote'     => 'reviews#downvote', as: :downvote_review
  post 'comments/:id/upvote'      => 'comments#upvote', as: :upvote_comment
  post 'comments/:id/downvote'    => 'comments#downvote', as: :downvote_comment
  post 'specialties/:id/upvote'   => 'specialties#upvote', as: :upvote_specialty
  post 'specialties/:id/downvote' => 'specialties#downvote', as: :downvote_specialty
  post 'restaurants/:restaurant_id/reviews/:id/comments' => 'comments#create'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # Refactor to featured stuff based on algorithm later
    @restaurant = Restaurant.find_by(id: 2) || Restaurant.all.sample
    @review = Review.all.sample
    @article = Article.all.sample
    if session[:visited]
    	render :index
    else
    	session[:visited] = true
    	render :splash, layout: false
    end
  end

  def splash
  	render :splash, layout: false
  end

end

app/views/welcome/_errors.html.erb
<div>
  <% if flash[:errors] %>
    <h3>Sorry, the following errors occurred.</h3>
    <ol>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ol>
  <% end %>

</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-7 col-xs-12">
      <%= image_tag("foodie_color.png", id: "site-logo", class: "img-responsive", alt: "Foodie Logo") %>
      <p class="main-welcome"><strong>Foodie</strong> is quite simply a site for lovers of food. Full of curated restaurant reviews and articles about every aspect of Chicago&rsquo;s food scene, it contains features written by local experts such as chefs, cookbook authors, and food critics.</p>
      <div id="welcome-images">
        <%= image_tag("arm.jpg", class: "img-responsive") %>
        <%= image_tag("thai.jpg", class: "img-responsive") %>
        <%= image_tag("duffs.jpg", class: "img-responsive") %>
      </div>
      <p class="main-welcome">The most active users of the site&mdash;those who are truly passionate and knowledgable about Chicago&rsquo;s food&mdash;will be invited to submit reviews after making a set number of contributions. All users can find reliable restaurant recommendations (including specific dish recommendations) based on neighborhood, cuisine, vegetarian options, or proximity.</p>

      <p class="main-welcome">And, unlike other restaurant-search sites, <strong>Foodie</strong> delivers a rating that has not been tarnished by restaurant goers who gripe about inattentive waiters, lighting, or lack of child-changing facilities. The score algorithm on <strong>Foodie</strong> ensures that only people who love good food as much as you have the power to affect a restaurant&rsquo;s rating.</p>

      <p class="main-welcome">Welcome and bon appetit!</p>
    </div>

    <div class="col-sm-5 hidden-xs">
      <p class="svg-intro-text">Click on a Chicago neighborhood to see its foodie-approved restaurants.</p>
      <div class="svg-wrapper"><%= inline_svg("neighborhoods.html.erb") %></div>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-4 col-xs-12 faux-panel" id="featured-review">
      <h2>Featured Review</h2>
      <div class="faux-panel-body">
        <h3 class="header-link text-capitalize"><%= link_to "#{@review.title}", restaurant_review_path(@review.restaurant, @review) %></h3>
        <p><strong>Review of <%= link_to "#{@review.restaurant.name}", restaurant_path(@review.restaurant) %> composed by <%= link_to "#{@review.reviewer.username}", user_path(@review.reviewer) %></strong></p>
        <p><%= @review.get_preview %>
          <%= link_to "read more...", restaurant_review_path(@review.restaurant, @review) %></p>
      <p>* * *</p>
      <p>See more from Chicago&rsquo;s <%= link_to "best food writers", top_reviewers_path %> best food writers elsewhere on the <strong>Foodie</strong> site.</p>
      </div>
    </div>

    <div class="col-sm-4 col-xs-12">
      <div class="faux-panel" id="featured-restaurant">
        <h2>Restaurant of the Day</h2>
        <div class="faux-panel-body">
          <h3 class="header-link"><%= link_to "#{@restaurant.name}", restaurant_path(@restaurant) %></h3>
          <div id="featured-restaurant-body">
            <p>This <%= @restaurant.cuisine %> eatery located in the trendy Chicago neighborhood <%= @restaurant.neighborhood %> offers delectable dishes and scores a <%= @restaurant.vegan_friendliness %> out of 5 on the vegan friendliness scale.</p>

            <p>Read foodie-approved reviews of <%= @restaurant.name %>, see recommended dishes, and much more by checking our <%= link_to "#{@restaurant.name} page", restaurant_path(@restaurant) %>.</p>
          <div id="restaurant-images">
            <%= image_tag("tds50.jpg", class: "img-responsive") %>
            <%= image_tag("pie.jpg", class: "img-responsive") %>
          </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4 col-xs-12 faux-panel" id="featured-article">
      <h2>Featured Article</h2>
      <div class="faux-panel-body">
        <h3 class="header-link text-capitalize"><%= link_to "#{@article.title}", article_path(@article) %></h3>
        <p><strong>Penned with love by <%= link_to "#{@article.author.username}", user_path(@article.author) %></strong></p>
        <p><%= @article.get_preview %>
          <%= link_to "read more...", article_path(@article) %></p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/splash.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Foodie.com</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag "splash" %>
</head>

<body>

<div class="overlay">
	<div class="overlay-menu">	
		<%= image_tag "foodie_color.png", id: "foodie" %>
		<div class="words">
			<h2>A new site for Chicago food lovers</h2>
			<ul>
				<li>Curated restaurant reviews</li>
				<li>Articles by top chefs and critics</li>
				<li>Dish recommendations</li>
			</ul>
		</div>

		<div class="access-buttons">
	    <%= button_to("SIGN UP!", new_user_registration_path, :method => :get) %>
	    <%= button_to("Enter Site", welcome_index_path, :method => :get) %>
		</div>
	</div>
</div>

</body>
</html>